/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartId = IDL.Text;
export const CartItem = IDL.Record({
  'size' : IDL.Nat8,
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat32,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'womenShoes' : IDL.Null,
  'menShoes' : IDL.Null,
  'kidsShoes' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Nat8),
  'stock' : IDL.Nat32,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat32,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Order = IDL.Record({
  'id' : IDL.Text,
  'total' : IDL.Nat32,
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addItemToCart' : IDL.Func([CartId, CartItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([CartId], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat32], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([CartId], [IDL.Vec(CartItem)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat32], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([CartId], [IDL.Text], []),
  'removeItemFromCart' : IDL.Func([CartId, IDL.Nat32, IDL.Nat8], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartId = IDL.Text;
  const CartItem = IDL.Record({
    'size' : IDL.Nat8,
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat32,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'womenShoes' : IDL.Null,
    'menShoes' : IDL.Null,
    'kidsShoes' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Nat8),
    'stock' : IDL.Nat32,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat32,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'total' : IDL.Nat32,
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addItemToCart' : IDL.Func([CartId, CartItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([CartId], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat32], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([CartId], [IDL.Vec(CartItem)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat32], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([CartId], [IDL.Text], []),
    'removeItemFromCart' : IDL.Func([CartId, IDL.Nat32, IDL.Nat8], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };